from typing import Protocol
from provozni_denik.domain.models import Visit


class VisitRepository(Protocol):
    def list_visits(self) -> list[Visit]: ...
    def arrive(self, person: str, room: str, purpose: str, escort: str, actor: str) -> int: ...
    def depart(self, visit_id: int, actor: str) -> None: ...
    def correct(self, visit_id: int, person: str, room: str, purpose: str,
                escort: str, actor: str, reason: str) -> None: ...
    def audit(self, visit_id: int | None = None) -> list[dict]: ...
