"""Ikony a metadata balíčku; bez spuštění PyInstalleru."""
import json
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

AUTHOR = "Miroslav Pospíšil"
DESCRIPTION = "provozní deník serverovny"
PRODUCT_NAME = "Provozní deník"


@dataclass(frozen=True)
class ReleaseVersion:
    tag: str
    numbers: tuple[int, int, int, int]

    @property
    def numeric(self) -> str:
        return ".".join(map(str, self.numbers))


def parse_tag(tag: str) -> ReleaseVersion:
    # Windows pevná verze má čtyři 16bitová čísla; textová verze zachová celý tag.
    match = re.fullmatch(r"v?(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?(?:[-+][0-9A-Za-z.-]+)?", tag)
    if not match:
        raise RuntimeError(f"Git tag {tag!r} nemá podporovaný tvar v1.2.3 nebo 1.2.3.4 (případně se suffixem).")
    numbers = tuple(int(part or 0) for part in match.groups())
    if any(number > 65535 for number in numbers):
        raise RuntimeError("Části verze pro Windows musí být v rozsahu 0–65535.")
    return ReleaseVersion(tag, numbers)


def git_version(root: Path) -> ReleaseVersion | None:
    try:
        result = subprocess.run(["git", "describe", "--tags", "--abbrev=0", "HEAD"],
                                cwd=root, check=True, capture_output=True, text=True, encoding="utf-8")
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None
    return parse_tag(result.stdout.strip())


def windows_version_text(version: ReleaseVersion | None) -> str:
    fields = {
        "CompanyName": AUTHOR,
        "Author": AUTHOR,
        "FileDescription": DESCRIPTION,
        "ProductName": PRODUCT_NAME,
        "OriginalFilename": "ProvozniDenik.exe",
        "InternalName": "ProvozniDenik",
    }
    if version is not None:
        fields.update(FileVersion=version.tag, ProductVersion=version.tag)
    numbers = version.numbers if version else (0, 0, 0, 0)
    strings = ",\n".join(f"                StringStruct({key!r}, {value!r})" for key, value in fields.items())
    return (
        "# UTF-8; generated by scripts/build_metadata.py\n"
        "VSVersionInfo(\n"
        f"    ffi=FixedFileInfo(filevers={numbers!r}, prodvers={numbers!r},\n"
        "                      mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),\n"
        "    kids=[StringFileInfo([StringTable('040504B0', [\n" + strings + "\n"
        "            ])]), VarFileInfo([VarStruct('Translation', [0x0405, 1200])])]\n"
        ")\n"
    )


def prepare_metadata(root: Path, platform: str | None = None) -> dict:
    platform = platform or sys.platform
    version = git_version(root)
    icons = root / "packaging/icons"
    icon = icons / ("app.ico" if platform == "win32" else "app.icns" if platform == "darwin" else "app.png")
    if not icon.is_file():
        raise RuntimeError(f"Chybí ikona: {icon}")
    output = root / "build" / platform / "metadata"
    output.mkdir(parents=True, exist_ok=True)
    version_file = output / "windows-version.txt"
    version_file.write_text(windows_version_text(version), encoding="utf-8")
    metadata_file = output / "_build_metadata.json"
    metadata_file.write_text(json.dumps({"version": version.tag if version else None, "author": AUTHOR,
                                         "description": DESCRIPTION}, ensure_ascii=False, indent=2), encoding="utf-8")
    return {"version": version, "icon": icon, "windows_version": version_file, "metadata": metadata_file}
